services:
  - type: web
    name: smart-hub-zoho-mock
    runtime: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ZOHO_API_KEY
        value: zoho-test-key-2024